name: 'push learning note'
description: 'test everyday'
# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'node18'
  main: 'README.md/action.js'